# Atividade - 25/09/23

Documentação Numpy: https://numpy.org/doc/stable/

Enviar este arquivo preenchido com o nome do aluno para o e-mail: profbrunorespostas1@gmail.com e assunto: AD2301

In [1]:
#Substituir nome do aluno aqui
print("Edenilson Lima de Freitas")

Edenilson Lima de Freitas


### Questão 1:
Pesquisar na documentação da biblioteca numpy por propriedades e funções disponíveis para manipulação de Array de 1 dimensão (1darray) que não foram vistas em sala de aula. Citar cada uma delas com a explicação em forma de comentário e um exemplo.

Arquivo da aula sobre numpy: https://github.com/brunogomesifrn/respostas_ifrn/blob/main/python/Aulas/2023/numpy.ipynb

#### Propriedades - 1darray

In [2]:
import numpy as np



In [9]:
# Criando um 1D array usando numpy.array()
my_array = np.array([1, 2, 3, 4, 5])

# Ou criando um 1D array usando numpy.arange()

my_array2 = np.arange(1, 6)  # Isso cria um array com os números de 1 a 5
print(my_array[0])  # Acessa o primeiro elemento (índice 0)
print(my_array[2])  # Acessa o terceiro elemento (índice 2)
print(my_array)





1
3
[1 2 3 4 5]


#### Funções - 1darray


Em NumPy, você pode realizar uma variedade de operações e funções em um 1D array (também conhecido como vetor) para manipular, analisar e processar dados de maneira eficiente. Aqui estão algumas funções comuns que você pode aplicar a um 1D array em Python usando NumPy:

Operações matemáticas básicas:

Você pode realizar operações matemáticas básicas em todos os elementos do array.

In [10]:
arr = np.array([1, 2, 3, 4, 5])

# Soma de todos os elementos do array
soma = np.sum(arr)

# Média dos elementos do array
media = np.mean(arr)

# Mínimo e máximo
minimo = np.min(arr)
maximo = np.max(arr)

# Raiz quadrada de cada elemento
raiz_quadrada = np.sqrt(arr)

In [27]:
# Imprime os resultados
print("Array:", arr)
print("Soma:", soma)
print("Média:", media)
print("Mínimo:", minimo)
print("Máximo:", maximo)
print("Raiz Quadrada:", raiz_quadrada)

Array: [1 2 3 4 5]
Soma: 15
Média: 3.0
Mínimo: 1
Máximo: 5
Raiz Quadrada: [1.         1.41421356 1.73205081 2.         2.23606798]


### Questão 2
Crie um exemplo de criação de um array de 2 dimensões (2darray).

Neste exemplo, matrix é um array de duas dimensões (uma matriz) que contém três linhas e três colunas. Cada lista interna representa uma linha da matriz, e os elementos dentro dessas listas representam os valores nas respectivas colunas.

In [28]:
# Criando um 2D array (uma matriz) com valores iniciais
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Imprimindo o 2D array
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Questão 3
Cite funções disponíveis no numpy que criam array de duas dimenões (2darray) já preenchido de forma automática.

In [29]:
# numpy.zeros(shape): Cria uma matriz preenchida com zeros.
zeros_matrix = np.zeros((3, 3))  # Cria uma matriz 3x3 preenchida com zeros
print(zeros_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# numpy.ones(shape): Cria uma matriz preenchida com uns.
ones_matrix = np.ones((2, 4))  # Cria uma matriz 2x4 preenchida com uns
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
# numpy.eye(N): Cria uma matriz de identidade N x N, com uns na diagonal principal e zeros em outros lugares.
identity_matrix = np.eye(3)  # Cria uma matriz de identidade 3x3
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
# numpy.random.rand(shape): Cria uma matriz com valores aleatórios entre 0 e 1.
random_matrix = np.random.rand(2, 3)  # Cria uma matriz 2x3 com valores aleatórios
print(random_matrix)

[[0.58027524 0.21346027 0.38657747]
 [0.6056106  0.51499292 0.0869283 ]]


In [33]:
# numpy.arange(start, stop, step): Cria uma matriz de valores igualmente espaçados dentro de um intervalo.
range_matrix = np.arange(1, 10, 2)  # Cria uma matriz com valores de 1 a 9 com passos de 2
print(range_matrix)

[1 3 5 7 9]


In [34]:
# numpy.linspace(start, stop, num): Cria uma matriz com valores igualmente espaçados dentro de um intervalo com base em um número especificado de pontos.
linspace_matrix = np.linspace(0, 1, 5)  # Cria uma matriz com 5 valores igualmente espaçados de 0 a 1
print(linspace_matrix)

[0.   0.25 0.5  0.75 1.  ]
