# Aula  - darray - Array de 2 dimensões

In [3]:
import numpy as np

## Criaçao de um 2darray

In [4]:
# utiliza tambem a funçao arra()
array_1 = np.array([[1,2,3,],[4,5,6]])

In [5]:
print(array_1)

[[1 2 3]
 [4 5 6]]


In [6]:
print(type(array_1))

<class 'numpy.ndarray'>


# Acessando elemnto do array de 2 dimensões

In [8]:
# sempre na sequencia: linha x coluna. se usa colchetes []
print(array_1[1][1])

5


In [9]:
# linha 0 ; coluna 2
print(array_1[0][2])

3


In [10]:
print(array_1[0][1])

2


In [11]:
# se substituir um valor se utiliza colchetes tambem
array_1[0][1]= 30
print(array_1)

[[ 1 30  3]
 [ 4  5  6]]


In [12]:
array_1[1,0]= 15
print(array_1)

[[ 1 30  3]
 [15  5  6]]


## propriedades para 2darray

In [13]:
# Shape - retorna a quantidade de elementos por dimensao
print(array_1.shape)

(2, 3)


In [14]:
# size - quantidade total de elementos no array
print(array_1.size)

6


In [15]:
# ndim - retorna a dimensao do array
print(array_1.ndim)

2


## Funções para 2darray

In [17]:
# cumsum() - soma acumulada
print(array_1.cumsum())

[ 1 31 34 49 54 60]


In [20]:
# reshape - modifica a dimensao do array
array_d1 = np.array([1,2,3,4,5,6])
array_2 = array_d1.reshape(2,3)
print(array_2)


[[1 2 3]
 [4 5 6]]


In [22]:
'''
A funçao cumsum() gera um array de 1 demensao. no exemplo a seguir foi acumulado com a funçao reshape(), que é executada
em seguida gerando gerando novamente o array de duas dimesões.
'''
print(array_1.cumsum().reshape(2,3))

[[ 1 31 34]
 [49 54 60]]


In [24]:
array_3 = np.array(range(1,11)).reshape(5,2)
print(array_3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
