# Numpy

numpy = Numerical python
pacote para operaçoes matematicas que suportam analise de dados, inteligentes artificial, entre outras.

- Numpy trabalha com o conceito de Array e tem suporte e leitura de datasers;
- Disponibilizam diversas funçoes de calculos matematicos e estatisticos;

Site Oficial: https://numpy.org


- Instalaçao: pip install numpy

## Array Numpy

Array é uma lista de dados de mesmo tipo.

Nomeclatura Ofical: ndarray
- 1-D array com 1 dimensao - vetor, lista
- 2- d array com 2 dimensao - matriz
- 3 - D ou mais array - array com 3 ou mais dimensoes - tensor

In [2]:
# Importando a biblioteca
import numpy as np

In [3]:
# Criando um array  - funçao array()
array_01 = np.array([2,6,5,1,55,])
print(array_01)


[ 2  6  5  1 55]


In [9]:
# type() - é uma funçao python para visualizar o tipo de dados 
array_01 = np.array([2,6,5,1,55,])
print(type(array_01))

<class 'numpy.ndarray'>


## Propriedades

In [10]:
# dtype -  imprime o tipo dos dados de array numpy
array_01 = np.array([2,6,5,1,55,])
print(array_01.dtype)

int32


In [11]:
# shape - dimensao qtd de elementos do array numpy
array_01 = np.array([2,6,5,1,55,])
print(array_01.shape)

(5,)


In [12]:
# size -  quantidade de elementos do array
array_01 = np.array([2,6,5,1,55,])
print(array_01.size)

5


## Funçoes

In [13]:
# cumsum() - gera um novo array numpy com a soma acumulada dos elementos
array_01 = np.array([2,6,5,1,55,])
print(array_01.cumsum())

[ 2  8 13 14 69]


In [17]:
# arange() - cria um array numpy surgerindo....
array_01 = np.arange(10)
print(array_01)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
array_01 = np.arange(2,10)
print(array_01)

[2 3 4 5 6 7 8 9]


In [16]:
array_01 = np.arange(2,10,2)
print(array_01)

[2 4 6 8]


In [20]:
'''
linpace() - gera m array numpy que: (1,10,4)
1 - numero inicial do intervalo
10 - numero final do intervalo
4 - deve preencher o array com 4 elementos deste intervalo com o mesmo espaçamento entre eles.
'''
array_01 = np.linspace(1,10,4)
print(array_01)

[ 1.  4.  7. 10.]


In [23]:
# qual() - compara elementos de arrays numpy resultado em um array de booleanos
array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.equal(array_02, array_03))

[False  True  True  True]


In [22]:
array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.array_equal(array_02, array_03))

False


## slicing de array numpy (fatiamento)

In [27]:
array_04 = np.arange(100)
print(array_04)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
array_05 = np.arange(25)
print(array_05)